# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build: .
    command: ./run.sh
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_NAME: app_db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"